### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by fa0311** [fa0311/twitter-openapi-typescript#1]
- [x] HomeTimeline
- [x] HomeLatestTimeline
- [x] ListLatestTweetsTimeline
- [x] UserByScreenName
- [x] TweetDetail
- [x] UserTweets
- [x] UserMedia
- [x] Likes
- [x] UserTweetsAndReplies
- [x] Bookmarks
- [x] ProfileSpotlightsQuery
- [x] Following
- [x] Followers

**Comment by thecodrr** [comment]
@fa0311 would love if you could regenerate the bindings with the latest openapi spec.
