### ISSUE TITLE
Required parameter "fieldToggles" was null or undefined when calling getUserTweetsAndReplies().

### ISSUE THREAD

**Issue by chenxhong** [fa0311/twitter-openapi-typescript#115]
When I update to the latest version, when using the method: getUserTweetsAndReplies, an error will be reported: Error [RequiredError]: Required parameter "fieldToggles" was null or undefined when calling getUserTweetsAndReplies().
How to use the latest version? How to pass fieldToggles parameter?

**Comment by chenxhong** [comment]
How to do this without using code: 
response = await client.getTweetApi().api.getUserTweetsAndReplies({
                    pathQueryId: client.flag.HomeTimeline.queryId,
                    variables: JSON.stringify(client.flag.HomeTimeline.variables),
                    features: JSON.stringify(client.flag.HomeTimeline.features),
                    fieldToggles:''
                  }); 
What about passing in the fieldToggles parameter?

**Comment by fa0311** [comment]
This is another dependency bug, fixed in v0.0.42
