### ISSUE TITLE
Count does not limit number of tweet results

### ISSUE THREAD

**Issue by simon-marcus** [fa0311/twitter-openapi-typescript#58]
I've noticed that setting the value of `count` in `getUserTweets` does not appear to limit the number of results: it returns 100 results by default. This would be really useful to make smaller requests.

```js
 const response = await client.getTweetApi().getUserTweets({userId: '44196397', count: 4});
```

I've reproduced the code here:
https://replit.com/@simonasaservice/TweetDemo#index.js

```js
import { TwitterOpenApi } from 'twitter-openapi-typescript';
const api = new TwitterOpenApi();

async function getTweets(userId) {
  const client = await api.getClient();
  const count = 5;
  const params = {
    userId: '44196397',
    count: count
  }
  console.log(`Should return ${count} results.`)
  const response = await client.getTweetApi().getUserTweets(params);

  const result = response.data.data;
  if (result) {
    console.log(`Response contains ${result.length} results.`)
    // console.log(result)
    return result
  }
  return null
}

getTweets();
```

Please let me know if there's anything else I could test, and thanks for this *outstanding* library! 🙏

**Comment by fa0311** [comment]
Thank you for sending us your Issues.
The count parameter exists in the official Twitter client, but seems to be ignored on the server side.

If logged in, it always returns 25 responses and if not logged in, it always seems to return 100 responses.

**Comment by simon-marcus** [comment]
Thank you for the fast reply! After additional testing, I think that the public API for `getUserTweets()` returns a selection of the most _popular_ tweets for some (maybe blue verified?) users—not the most _recent_ tweets. It won't return any results at all for other users. I have updated my [code](https://replit.com/@simonasaservice/TweetDemo#index.js) with some examples if you want to see.

To get reliable results, I will need to to use a logged-in version of the API. Is there a version that you have been working on? I see you mention the [Logged in branch](https://github.com/fa0311/TwitterInternalAPIDocument/tree/twitter-login), but I am not clear on how I should use this. I would be grateful for your suggestion!

**Comment by fa0311** [comment]
`getUserTweets({ userId })` is the same as the tweets you get when you visit `https://twitter.com/<screenName>`

The csrf token and auth token are required to use the login version of the API.
```ts
const client = await api.getClientFromCookies('<csrf toke>', '<auth token>');
await client.getUserApi().getUserTweets({ userId });
```

You need the cookie that is given to you after you log in with your browser.
`ct0` is the csrf token and `auth_token` is the auth token.

An external program is needed to automate this process.
As far as I know, this is all there is, except for implementations using WebDriver and older implementations.

Recommend (Python)
https://github.com/tsukumijima/tweepy-authlib
My implementation (Python)
https://github.com/fa0311/TwitterFrontendFlow
