### ISSUE TITLE
Typo in GetHomeTimelineParam

### ISSUE THREAD

**Issue by Redcrafter** [fa0311/twitter-openapi-typescript#62]
As the titele implies there's a typo in GetHomeTimelineParam. 'couser' should be spelled 'cursor'.

https://github.com/fa0311/twitter-openapi-typescript/blob/7eb4be3fe68bef8f6965f3941d5c12f4c73e4f51/twitter-openapi-typescript/src/apis/tweetApi.ts#L26
https://github.com/fa0311/twitter-openapi-typescript/blob/7eb4be3fe68bef8f6965f3941d5c12f4c73e4f51/twitter-openapi-typescript/src/apis/tweetApi.ts#L150

**Comment by fa0311** [comment]
Fixed in 0.0.18
