### ISSUE TITLE
ResponseError: Response returned an error code

### ISSUE THREAD

**Issue by aegie4** [fa0311/twitter-openapi-typescript#69]
When I call `getHomeLatestTimeline()` or `getTweetDetail()` (and I assume any other api call) I get an error: `ResponseError: Response returned an error code`

It happens here:
https://github.com/fa0311/twitter-openapi-typescript/blob/145a39cc1318c6015d2192d24f338f4a18a5477a/twitter-openapi-typescript-generated/src/runtime.ts#L140
For some reason `response` is `{}` (empty object)

I'm using the latest versions: `twitter-openapi-typescript 0.0.19` `twitter-openapi-typescript-generated 0.0.12`

My code worked a week ago when I used `twitter-openapi-typescript` version `0.0.17`

I'm using Deno.

**Comment by fa0311** [comment]
This did not happen in my environment (node 18).
I changed the authentication process in twitter-openapi-typescript 0.0.19 but did not update the documentation.

**Comment by aegie4** [comment]
I fixed the call to `getClientFromCookies()` according to the updated documentation and it works now. Thank you!
