### ISSUE TITLE
getUserTweets param: count is invalid

### ISSUE THREAD

**Issue by chenxhong** [fa0311/twitter-openapi-typescript#83]
const { TwitterOpenApi } = require("twitter-openapi-typescript")
const { TwitterApi } = require('twitter-api-v2')

const login = async () => {
    const cookie = { auth_token: 'e0471249ac5046ae50bb4aa52abecb8fbc4f7aa8', ct0: 'aca579f883153400d3520b8e76237cc6898df12d9d22280e55f56c02fba992c9c13b0f4c9e8271b77758426262dd7e3d156c98538b73d137dc5c179eebe6a03445114b3a2100996bdca020b528a8a415' };
    const api = new TwitterOpenApi({ fetchApi: fetch });
    const client = await api.getClientFromCookies(cookie);
    const plugin = {
        onBeforeRequest: async (params) => {
            params.computedParams.headers = {
                ...params.computedParams.headers,
                ...TwitterOpenApi.api_key,
                'x-csrf-token': cookie.ct0,
                'x-twitter-auth-type': 'OAuth2Session',
                authorization: `Bearer ${TwitterOpenApi.bearer}`,
                cookie: api.cookieEncode(cookie),
            };
            params.requestOptions.headers = {
                ...params.requestOptions.headers,
                ...TwitterOpenApi.api_key,
                'x-csrf-token': cookie.ct0,
                'x-twitter-auth-type': 'OAuth2Session',
                authorization: `Bearer ${TwitterOpenApi.bearer}`,
                cookie: api.cookieEncode(cookie),
            };
        },
    };
    const legacy = new TwitterApi('_', { plugins: [plugin] });
    return { client, legacy };
}

const user_id = async () => {
    const { client, legacy } = await login();
    const response = await client.getTweetApi().getUserTweets({ userId: '44196397', count: 3 });
    console.log(response.data.data.length)
}

user_id()

get the result: 25

As above, I set the count to 3, but I still received more than 3 tweets.

**Comment by fa0311** [comment]
Please check this out.
https://github.com/fa0311/twitter-openapi-typescript/issues/58

**Comment by fa0311** [comment]
``
