### ISSUE TITLE
How to set proxy

### ISSUE THREAD

**Issue by chenxhong** [fa0311/twitter-openapi-typescript#84]
How to set proxy?

**Comment by fa0311** [comment]
Does not support proxies because it uses Node-fetch
But I found a package that may be helpful and will support this
https://www.npmjs.com/package/https-proxy-agent

**Comment by chenxhong** [comment]
So if you want to use proxy, you need to modify the source code, right?

**Comment by fa0311** [comment]
That's right.
If you would like to contribute, you are welcome to do so.

**Comment by fa0311** [comment]
Added proxy support in v0.0.27.
Sample code can be found here.
https://github.com/fa0311/twitter-openapi-typescript/blob/master/example/src/proxy.ts
