### ISSUE TITLE
How to quote a tweet?

### ISSUE THREAD

**Issue by darkmasta** [fa0311/twitter-openapi-typescript#85]
How can we quote a tweet instead of retweeting? It would be nice if you added this feature too. 🙏🙏

![image](https://github.com/fa0311/twitter-openapi-typescript/assets/1842459/9d9ab545-1e5d-4860-84da-f8170705d097)

**Comment by darkmasta** [comment]
I figured out how to do it...

**Comment by darkmasta** [comment]
This solved my problem. I am able to quote a tweet this way.

```
const tweetUrl = `https://twitter.com/elonmusk/status/1748595664131363231`;
const status = `HELLO QUOTE TWEET ${tweetUrl}`;

const response = await client.getPostApi().postCreateTweet({
  tweetText: tweetUrl,
  mediaIds: [],
})
```

**Comment by fa0311** [comment]
> This solved my problem. I am able to quote a tweet this way.

The Twitter API v2 implemented quote RT in the same way, but the current GraphQL client does not.
I don't know why the v2 way works fine.

**Comment by darkmasta** [comment]
> The Twitter API v2 implemented quote RT in the same way, but the current GraphQL client seems to implement it differently.
I don't know why the v2 way of writing works fine for graphQL endpoints.

I am not sure but they extract info from tweet text and update the tweet with that info. You can post an image url from twitter and it becomes tweet media as well. There is a tweet text processing going on.
