### ISSUE TITLE
Use the proxy, whith one error:

### ISSUE THREAD

**Issue by chenxhong** [fa0311/twitter-openapi-typescript#92]
Use the proxy, error:
/node_modules/node-fetch/lib/index.js:273
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://raw.githubusercontent.com/fa0311/twitter-openapi/7560ee63488ec9d15f5389e64867f2413701d7dd/src/config/placeholder.json reason: Unexpected token '<', "<html>
<h"... is not valid JSON
    at /node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}

**Comment by fa0311** [comment]
This is not enough information.
Please check if you can access github through a proxy
